SDL_INCLUDE_DIRS = {
	path.join(AETHER_EXTERNALS_DIR, "sdl/include"),
	path.join(AETHER_EXTERNALS_DIR, "sdl/src/hidapi/hidapi"),
}

SDL_COMMON_SOURCES = {
	path.join(AETHER_EXTERNALS_DIR, "sdl/include/*.h"),
	path.join(AETHER_EXTERNALS_DIR, "sdl/src/*.c"),
	path.join(AETHER_EXTERNALS_DIR, "sdl/src/**.h"),	
	path.join(AETHER_EXTERNALS_DIR, "sdl/src/atomic/*.c"),
	path.join(AETHER_EXTERNALS_DIR, "sdl/src/audio/*.c"),
	path.join(AETHER_EXTERNALS_DIR, "sdl/src/audio/dummy/*.c"),
	path.join(AETHER_EXTERNALS_DIR, "sdl/src/audio/disk/*.c"),
	path.join(AETHER_EXTERNALS_DIR, "sdl/src/cpuinfo/*.c"),
	path.join(AETHER_EXTERNALS_DIR, "sdl/src/dynapi/*.c"),
	path.join(AETHER_EXTERNALS_DIR, "sdl/src/events/*.c"),
	path.join(AETHER_EXTERNALS_DIR, "sdl/src/file/*.c"),
	path.join(AETHER_EXTERNALS_DIR, "sdl/src/haptic/*.c"),
	path.join(AETHER_EXTERNALS_DIR, "sdl/src/haptic/dummy/*.c"),
	path.join(AETHER_EXTERNALS_DIR, "sdl/src/joystick/*.c"),
	path.join(AETHER_EXTERNALS_DIR, "sdl/src/joystick/hidapi/*.c"),
	path.join(AETHER_EXTERNALS_DIR, "sdl/src/joystick/virtual/*.c"),
	path.join(AETHER_EXTERNALS_DIR, "sdl/src/power/*.c"),
	path.join(AETHER_EXTERNALS_DIR, "sdl/src/render/*.c"),
	path.join(AETHER_EXTERNALS_DIR, "sdl/src/render/software/*.c"),
	path.join(AETHER_EXTERNALS_DIR, "sdl/src/sensor/*.c"),
	path.join(AETHER_EXTERNALS_DIR, "sdl/src/sensor/dummy/*.c"),
	path.join(AETHER_EXTERNALS_DIR, "sdl/src/stdlib/*.c"),
	path.join(AETHER_EXTERNALS_DIR, "sdl/src/thread/*.c"),
	path.join(AETHER_EXTERNALS_DIR, "sdl/src/timer/*.c"),
	path.join(AETHER_EXTERNALS_DIR, "sdl/src/timer/dummy/*.c"),
	path.join(AETHER_EXTERNALS_DIR, "sdl/src/video/*.c"),
	path.join(AETHER_EXTERNALS_DIR, "sdl/src/video/dummy/*.c"),
	path.join(AETHER_EXTERNALS_DIR, "sdl/src/video/yuv2rgb/*.c"),
	path.join(AETHER_EXTERNALS_DIR, "sdl/src/locale/*.c"),
}

SDL_LINUX_SOURCES = {
	path.join(AETHER_EXTERNALS_DIR, "config/sdl/linux/include/*.h"),
	path.join(AETHER_EXTERNALS_DIR, "sdl/src/audio/pulseaudio/*.c"),
	path.join(AETHER_EXTERNALS_DIR, "sdl/src/audio/dsp/*.c"),
	path.join(AETHER_EXTERNALS_DIR, "sdl/src/audio/alsa/*.c"),
	path.join(AETHER_EXTERNALS_DIR, "sdl/src/core/linux/*.c"),
	path.join(AETHER_EXTERNALS_DIR, "sdl/src/atomic/SDL_atomic.c"),
	path.join(AETHER_EXTERNALS_DIR, "sdl/src/atomic/SDL_spinlock.c"),
	path.join(AETHER_EXTERNALS_DIR, "sdl/src/haptic/linux/*.c"),
	path.join(AETHER_EXTERNALS_DIR, "sdl/src/joystick/linux/*.c"),
	path.join(AETHER_EXTERNALS_DIR, "sdl/src/joystick/steam/*.c"),
	path.join(AETHER_EXTERNALS_DIR, "sdl/src/power/linux/*.c"),
	path.join(AETHER_EXTERNALS_DIR, "sdl/src/filesystem/unix/*.c"),
	path.join(AETHER_EXTERNALS_DIR, "sdl/src/video/wayland/*.c"),
	path.join(AETHER_EXTERNALS_DIR, "sdl/src/video/x11/*.c"),
	path.join(AETHER_EXTERNALS_DIR, "sdl/src/render/opengl/*.c"),
	path.join(AETHER_EXTERNALS_DIR, "sdl/src/render/opengles/*.c"),
	path.join(AETHER_EXTERNALS_DIR, "sdl/src/render/opengles2/*.c"),
	path.join(AETHER_EXTERNALS_DIR, "sdl/src/libm/*.c"),
}

SDL_WIN_SOURCES = {
	path.join(AETHER_EXTERNALS_DIR, "sdl/src/audio/directsound/*.c"),
	path.join(AETHER_EXTERNALS_DIR, "sdl/src/audio/winmm/*.c"),
	path.join(AETHER_EXTERNALS_DIR, "sdl/src/audio/xaudio2/*.c"),
	path.join(AETHER_EXTERNALS_DIR, "sdl/src/audio/wasapi/*.c"),		
	path.join(AETHER_EXTERNALS_DIR, "sdl/src/haptic/windows/*.c"),
	path.join(AETHER_EXTERNALS_DIR, "sdl/src/hidapi/windows/*.c"),
	path.join(AETHER_EXTERNALS_DIR, "sdl/src/joystick/windows/*.c"),
	path.join(AETHER_EXTERNALS_DIR, "sdl/src/thread/windows/*.c"),
	path.join(AETHER_EXTERNALS_DIR, "sdl/src/thread/generic/SDL_syscond.c"),
	path.join(AETHER_EXTERNALS_DIR, "sdl/src/video/windows/*.c"),
	path.join(AETHER_EXTERNALS_DIR, "sdl/src/core/windows/*.c"),
	path.join(AETHER_EXTERNALS_DIR, "sdl/src/filesystem/windows/*.c"),
	path.join(AETHER_EXTERNALS_DIR, "sdl/src/loadso/windows/*.c"),
	path.join(AETHER_EXTERNALS_DIR, "sdl/src/power/windows/*.c"),
	path.join(AETHER_EXTERNALS_DIR, "sdl/src/timer/windows/*.c"),
	path.join(AETHER_EXTERNALS_DIR, "sdl/src/render/direct3d/*.c"),
	path.join(AETHER_EXTERNALS_DIR, "sdl/src/render/direct3d11/*.c"),
	path.join(AETHER_EXTERNALS_DIR, "sdl/src/render/opengl/*.c"),
    path.join(AETHER_EXTERNALS_DIR, "sdl/src/render/opengles/*.c"),
    path.join(AETHER_EXTERNALS_DIR, "sdl/src/render/opengles2/*.c"),
    path.join(AETHER_EXTERNALS_DIR, "sdl/src/locale/windows/*.c"),
    path.join(AETHER_EXTERNALS_DIR, "sdl/src/sensor/windows/*.c"),
	path.join(AETHER_EXTERNALS_DIR, "sdl/src/libm/*.c"),
	path.join(AETHER_EXTERNALS_DIR, "sdl/src/main/windows/*.c"),
}

SDL_MINGW_SOURCES = {
	path.join(AETHER_EXTERNALS_DIR, "sdl/src/audio/directsound/*.c"),
	path.join(AETHER_EXTERNALS_DIR, "sdl/src/audio/winmm/*.c"),
	path.join(AETHER_EXTERNALS_DIR, "sdl/src/audio/wasapi/*.c"),
	path.join(AETHER_EXTERNALS_DIR, "sdl/src/haptic/windows/*.c"),
	path.join(AETHER_EXTERNALS_DIR, "sdl/src/hidapi/windows/*.c"),
	path.join(AETHER_EXTERNALS_DIR, "sdl/src/joystick/windows/*.c"),
	path.join(AETHER_EXTERNALS_DIR, "sdl/src/thread/windows/*.c"),
	path.join(AETHER_EXTERNALS_DIR, "sdl/src/thread/generic/SDL_syscond.c"),
	path.join(AETHER_EXTERNALS_DIR, "sdl/src/video/windows/*.c"),
	path.join(AETHER_EXTERNALS_DIR, "sdl/src/core/windows/*.c"),
	path.join(AETHER_EXTERNALS_DIR, "sdl/src/filesystem/windows/*.c"),
	path.join(AETHER_EXTERNALS_DIR, "sdl/src/loadso/windows/*.c"),
	path.join(AETHER_EXTERNALS_DIR, "sdl/src/power/windows/*.c"),
	path.join(AETHER_EXTERNALS_DIR, "sdl/src/timer/windows/*.c"),
	path.join(AETHER_EXTERNALS_DIR, "sdl/src/render/direct3d/*.c"),
	path.join(AETHER_EXTERNALS_DIR, "sdl/src/render/opengl/*.c"),
    path.join(AETHER_EXTERNALS_DIR, "sdl/src/render/opengles/*.c"),
    path.join(AETHER_EXTERNALS_DIR, "sdl/src/render/opengles2/*.c"),		
	path.join(AETHER_EXTERNALS_DIR, "sdl/src/libm/*.c"),
}